// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJn3_8y4cnClJiexh44uq7pl9aO7RXqeA',
    appId: '1:1090933945004:web:89d24f324057d1fcf92509',
    messagingSenderId: '1090933945004',
    projectId: 'proyectofinalandroid-a7d02',
    authDomain: 'proyectofinalandroid-a7d02.firebaseapp.com',
    storageBucket: 'proyectofinalandroid-a7d02.appspot.com',
    measurementId: 'G-4QGPE43B7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtYJLual-Ru8soptEqY-hN5oivTWbu-B4',
    appId: '1:1090933945004:android:208680a135c92783f92509',
    messagingSenderId: '1090933945004',
    projectId: 'proyectofinalandroid-a7d02',
    storageBucket: 'proyectofinalandroid-a7d02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZBWE66vFLGEhuC841xUZDyZexZuuGRxY',
    appId: '1:1090933945004:ios:b8cdad50002a8068f92509',
    messagingSenderId: '1090933945004',
    projectId: 'proyectofinalandroid-a7d02',
    storageBucket: 'proyectofinalandroid-a7d02.appspot.com',
    iosClientId: '1090933945004-u1qhcefgudkqmsvp6c9rsf0p1nn94dop.apps.googleusercontent.com',
    iosBundleId: 'com.example.cineScope',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZBWE66vFLGEhuC841xUZDyZexZuuGRxY',
    appId: '1:1090933945004:ios:83e6dcd865d5147cf92509',
    messagingSenderId: '1090933945004',
    projectId: 'proyectofinalandroid-a7d02',
    storageBucket: 'proyectofinalandroid-a7d02.appspot.com',
    iosClientId: '1090933945004-vmg4lkk9pvsmhfn9ibacg84mr4qldthh.apps.googleusercontent.com',
    iosBundleId: 'com.example.cineScope.RunnerTests',
  );
}
